/** 
  * @desc This file definess all the events that rules the API
  * @author Michael Avilán michael.avilan@gmail.com
*/

var AdPlatformsController={
	//FACEBOOK
	LIBRARIES_LOADED_EVENT:'LIBRARIES_LOADED_EVENT',
	FACEBOOK_CLASSICTAG_DISPATCHED_EVENT:'FACEBOOK_CLASSICTAG_DISPATCHED_EVENT',
	FACEBOOK_CONVERSIONTAG_DISPATCHED_EVENT:'FACEBOOK_CONVERSIONTAG_DISPATCHED_EVENT',
	FACEBOOK_AUDIENCETAG_DISPATCHED_EVENT:'FACEBOOK_AUDIENCETAG_DISPATCHED_EVENT',
	//GOOGLE
	GOOGLE_ADWORDS_DISPATCHED_EVENT:'GOOGLE_ADWORDS_DISPATCHED_EVENT',
	DOUBLE_CLICK_DISPATCHED_EVENT:'DOUBLE_CLICK_DISPATCHED_EVENT',
	DOUBLE_CLICK_DSP_DISPATCHED_EVENT:'DOUBLE_CLICK_DSP_DISPATCHED_EVENT',
	//SIZMEK
	SIZMEK_COUNTER_DISPATCHED_EVENT:'SIZMEK_COUNTER_DISPATCHED_EVENT',
	SIZMEK_REMARKETING_DISPATCHED_EVENT:'SIZMEK_REMARKETING_DISPATCHED_EVENT',
	SIZMEK_SALES_DISPATCHED_EVENT:'SIZMEK_SALES_DISPATCHED_EVENT',
	//SOICOS
	SOICOS_TAG_DISPATCHER:'SOICOS_TAG_DISPATCHER',
	SOICOS_IMAGE_TAG_DISPATCHER:'SOICOS_IMAGE_TAG_DISPATCHER',
};